### ISSUE TITLE
Settings open but no start Moto g6

### ISSUE THREAD

**Issue by hobbowizard** [v3rm0n/m8c-android#128]
Get into settings but no matter what configuration I choose it won't start upon pressing start. Am I doing something wrong?

**Comment by v3rm0n** [comment]
Is the device otherwise working? You can try https://m8.run in a Chrome browser as well to see if it works

**Comment by hobbowizard** [comment]
Forgive my ignorance but do I have to have the micro control?

**Comment by v3rm0n** [comment]
This is just an app that lets you connect to the Teensy microcontroller over USB, you need a Teensy with M8 Headless firmware installed to use this application.

**Comment by hobbowizard** [comment]
Ok sorry about that

**Comment by v3rm0n** [comment]
No worries, I'll close this issue then :)
