### ISSUE TITLE
lags on android 14 and firmware 4

### ISSUE THREAD

**Issue by nnonickreal** [v3rm0n/m8c-android#228]
hi! 
when i move the cursor, the screen starts flickering, sound crackles, cursor sometimes returns to the position where it was, sometimes part of the screen freezes.
device: redmi pad 2022 (android 14 hyperos)

https://github.com/user-attachments/assets/351b859e-8c40-4e4a-8000-f1771d874123

**Comment by v3rm0n** [comment]
Hi, yes that's a known issue, the serial traffic interferes with the audio traffic.

**Comment by nnonickreal** [comment]
how can i fix it?

**Comment by v3rm0n** [comment]
Not 100% sure but if somebody with some knowledge of isochronous USB transfer could rewrite the userspace audio driver implementation then it might help
