### ISSUE TITLE
State not saved after disconnecting

### ISSUE THREAD

**Issue by YoelFievelBenAvram** [v3rm0n/m8c-android#231]
There does not appear to be any way to close the app in a way that preserves the device state. You can save songs to the sd, but unsaved edits will not persist following a disconnect. Without a gamepad attached, there's no way to hit the quit button. And even with a gamepad, the function doesn't appear to work. Force stopping the app similarly does not seem to trigger the m8 to save state.

**Comment by v3rm0n** [comment]
This is a hardware issue: the M8 does not have a way to preserve the state without a battery. It works on the real device because it has one.

**Comment by YoelFievelBenAvram** [comment]
It works fine with m8c on arkos and Linux.

**Comment by v3rm0n** [comment]
Thanks a lot for the info, I'll try to check if there's something missing.

**Comment by v3rm0n** [comment]
@YoelFievelBenAvram have you tried pressing up and down at the same time, does it persist the state then?

**Comment by YoelFievelBenAvram** [comment]
I can confirm that works! It does save state when backing into settings. I don't use that feature a ton because the readme kinda says not to in respect to closing, and there's a different bug where after you back into settings, you can't go back into the editing screen without disconnecting the headless. So I usually just pull and replug to change settings. Also, I usually use a gamepad so I tend to keep the buttons hidden. But it certainly does work! Thanks for your help, and great work on the app. The effort is absolutely appreciated.

**Comment by YoelFievelBenAvram** [comment]
Up and down on the touch screen work to save state. On latest Android with firmware, select and right click work to save state as well.
