### ISSUE TITLE
Crashing on multiple platforms

### ISSUE THREAD

**Issue by MarcoDjallo** [v3rm0n/m8c-android#81]
Hello, I'm trying to use this app, but no matter the phone I use, it crashes as soon as I press start.

I tried it on

- Poco F2 with Android 13
- Nexus 5X with Android 10
- Xperia XA2 with Android 9

for each one, I tried every possible combination of audio device and audio driver, but the result doesn't change: as soon as I press the "start" button, the app switch to a grey screen, then crashes.

My Teensy 4.1 have the latest headless M8 firmware flashed on it, and using it through Chromium and M8WebDisplay works well.

Something I can do to help troubleshoot?

Thanks a lot

**Comment by v3rm0n** [comment]
Try this version https://github.com/v3rm0n/m8c-android/releases/tag/v1.0.17
