### ISSUE TITLE
Haptic feedback ?

### ISSUE THREAD

**Issue by Jeymadcat** [v3rm0n/m8c-android#83]
do you think it's possible to add this haptic feedback function on the touch controls, it would be so practical and more lively; )

thank !

**Comment by v3rm0n** [comment]
Couldn't get it to work on my phone, but added it anyway so you can try it out and let me know if it works for you https://github.com/v3rm0n/m8c-android/releases/tag/v1.0.17

**Comment by Jeymadcat** [comment]
Reallly Thank You !!! its perfect ;  )

**Comment by Jeymadcat** [comment]
Thanks
