### ISSUE TITLE
Edit Hold - Fx Menu

### ISSUE THREAD

**Issue by Jeymadcat** [v3rm0n/m8c-android#91]
Hello 
the fx menu does not remain available in touch mode, as soon as you release the buttons on the screen, it makes the selection difficult but the haptic feedback is present and very satisfying but this little problem spoils the pleasure a little, of course, it must work better with a externe pad!  could you perhaps add a button that would bring together the combo of the Edit button or be able to maintain / hold it so that the fx menu does not disappear when your fingers are released, that would be great!  it's missing that ^^.  Thanks in advance if you find a tip.

**Comment by MarcoDjallo** [comment]
I confirm this. On the M8 we display app, this works like this: keeping pressed the modify button keeps the menu opened, and you can navigate with the directional buttons. As soon as you leave the other button, the menu closes selecting the effect you were on.

**Comment by v3rm0n** [comment]
Should be fixed in https://github.com/v3rm0n/m8c-android/releases/tag/v1.0.23

**Comment by Jeymadcat** [comment]
it's better like that yes, but the instrument fx menu is missing, we don't see it appear!  only sequencer fx and mixer effect x (

**Comment by Jeymadcat** [comment]
Perfect !! thanks you !!
